# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target 'APIClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APIClient

end

target 'MyEmbedFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'

  target 'MyEmbedFrameworkTests' do
    # Pods for testing
  end

end

target 'SampleiOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleiOSApp
  pod 'SDWebImage'

  target 'SampleiOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleiOSAppUITests' do
    # Pods for testing
  end

end
